ktor:
  deployment:
    host: localhost
    port: 8080
  application:
    modules:
      - com.github.yuk1ty.todoAppKt.ApplicationKt.module
db:
  read:
    driverClassName: "org.postgresql.Driver"
    jdbcURL: "jdbc:postgresql://localhost:5432/todo_app_kt"
    user: "readonly"
    password: "password"
  write:
    driverClassName: "org.postgresql.Driver"
    jdbcURL: "jdbc:postgresql://localhost:5432/todo_app_kt"
    user: "writable"
    password: "password"